### ISSUE TITLE
Intermittent fails

### ISSUE THREAD

**Issue by cjfields** [bioperl/Bio-Procedural#3]
Seems related to `Module::Build` (and maybe `Bio::Root::Build`?)

Example:

http://matrix.cpantesters.org/?dist=Bio-Procedural%201.7.4;os=linux;perl=5.28.0;reports=1

**Comment by carandraug** [comment]
Last time this was because of trying to use the `test_skip` from `Bio::Root::Test` to decide whether network is available (I thought this was already fixed in the bioperl core distribution).

This should be replaced with `Test::RequiresInternet` (easier to put those in a separate test file as well).

**Comment by eserte** [comment]
The following backtrace appears when running the failing test with `perl -d`:
```
Can't find 'build_params' in _build at /usr/perl5.8.9/lib/site_perl/5.8.9/Module/Build/Base.pm line 1291.
 at /usr/perl5.8.9/lib/site_perl/5.8.9/Module/Build/Base.pm line 1291.
        Module::Build::Base::read_config(Module::Build=HASH(0x80697a5e0)) called at /usr/perl5.8.9/lib/site_perl/5.8.9/Module/Build/Base.pm line 78
        Module::Build::Base::resume("Module::Build") called at /usr/perl5.8.9/lib/site_perl/5.8.9/Module/Build/Base.pm line 137
        Module::Build::Base::current("Module::Build") called at /usr/perl5.8.9/lib/site_perl/5.8.9/Bio/Root/Test.pm line 359
        Bio::Root::Test::test_network() called at /usr/perl5.8.9/lib/site_perl/5.8.9/Bio/Root/Test.pm line 502
        Bio::Root::Test::_skip("-tests", 12, "-requires_networking", 1, "-requires_module", "LWP::UserAgent") called at /usr/perl5.8.9/lib/site_perl/5.8.9/Bio/Root/Test.pm line 274
        Bio::Root::Test::test_skip("-tests", 12, "-requires_networking", 1, "-requires_module", "LWP::UserAgent") called at t/Perl.t line 64
```

**Comment by eserte** [comment]
`Module::Build->current` is only valid if within a MB-based distribution --- but Bio-Procedural is using Makefile.PL:
```
$ perl5.8.9 -MModule::Build -e 'warn Module::Build->current()' 
Can't find 'build_params' in _build at /usr/perl5.8.9/lib/site_perl/5.8.9/Module/Build/Base.pm line 1291.
```

**Comment by cjfields** [comment]
This looks like it may be from the dzil-generated Makefile. A `Dist::Zilla` bug?  Or maybe our plugin?

**Comment by cjfields** [comment]
Ah nevermind, it's not the Build but at the test level. I think @carandraug's recommended fix is best.

**Comment by carandraug** [comment]
This is now fixed but the test to connect to refseq database fail on my end (the issue was already there before).
